const ACTIONS = {
    LOAD_POSTS: "LOAD_POSTS",
    LIKE_POST: "LIKE_POST",
    COMMENT_ON_POST: "COMMENT_ON_POST",
    VIEW_OWN_COMMENTS: "VIEW_OWN_COMMENTS",
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    INCREASE_NEW_POSTS_COUNT: "INCREASE_NEW_POSTS_COUNT"
}

export default ACTIONS